In [ ]:
import pandas as pd
import numpy as np
columns = [
    'date', 'msg_id', 'from', 'newsgroups',
    'subject', 'references', 'start', 'length'
]

df=pd.read_csv('/Users/gga/Downloads/usenetstuff/alt.politics.british.20140613.mbox.csv.gz',compression='gzip',on_bad_lines='skip',names=columns,sep='\t',header=None)

print(df.head())

In [59]:
df=df[1:].reset_index(drop=True)

In [60]:
#df.drop(columns='index',inplace=True)

In [ ]:
df.info()

In [ ]:
df.head()

In [ ]:
df.isnull().sum()

In [64]:
df_messages=pd.read_csv('/Users/gga/Downloads/usenetstuff/alt.politics.british.20140613.mbox.gz',compression='gzip',on_bad_lines='skip',names=columns,header=None,sep='\t',encoding='latin1')

/var/folders/9h/7mtmy98n0jl_fwz3rzx0_k300000gn/T/ipykernel_14389/4280013873.py:1: DtypeWarning: Columns (1,2,3,4,5,6,7) have mixed types. Specify dtype option on import or set low_memory=False.
  df_messages=pd.read_csv('/Users/gga/Downloads/usenetstuff/alt.politics.british.20140613.mbox.gz',compression='gzip',on_bad_lines='skip',names=columns,header=None,sep='\t',encoding='latin1')

In [65]:
df_messages.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 68001705 entries, 0 to 68001704
Data columns (total 8 columns):
 #   Column      Dtype
---  ------      -----
 0   date        object
 1   msg_id      object
 2   from        object
 3   newsgroups  object
 4   subject     object
 5   references  object
 6   start       object
 7   length      object
dtypes: object(8)
memory usage: 4.1+ GB

In [66]:
#new_col=df_messages.columns.str.split()
#new_col

In [67]:
#df_messages=pd.read_csv('/Users/gga/Downloads/usenetstuff/alt.politics.british.20140613.mbox.gz',compression='gzip',on_bad_lines='skip',encoding='latin1')

In [68]:
df_messages['date'].iloc[100]

'I understand that there is a particularly strong movement in Scotland'

In [69]:
df_messages['date'].iloc[50]

'Xref: intern1.nntp.aus1.giganews.com alt.politics.british:760756'

In [70]:
df['references'].iloc[0]

'<9s2Ja.254938$ro6.6586887@news2.calgary.shaw.ca> <aakbfv4rhji27jfocoqh3vdagb0e6hvvki@4ax.com>'

In [71]:
df_messages['date'].iloc[53]

' alt.conspiracy.jfk:297256'

In [72]:
df_messages.iloc[100]

date          I understand that there is a particularly stro...
msg_id                                                      NaN
from                                                        NaN
newsgroups                                                  NaN
subject                                                     NaN
references                                                  NaN
start                                                       NaN
length                                                      NaN
Name: 100, dtype: object

In [73]:
df_messages_new=pd.read_csv('/Users/gga/Downloads/usenetstuff/alt.politics.british.20140613.mbox.gz',compression='gzip',on_bad_lines='skip',encoding='latin1')

In [ ]:
df_messages_new.iloc[140:160]

In [ ]:
df_messages_new

In [76]:
df_messages_new.iloc[0:30]

                 From nobody Fri Jun 13 18:36:02 2014
0   Path: news5.aus1.giganews.com!firehose2!nntp4!...
1   From: "Andrew Fenton" <andrew-fenton@spammers....
2                         alt.politics.usa.republican
3                References: <3ef17faa@212.67.96.135>
4    <Cc1Ja.1314$SJ5.11403450@news-text.cableinet....
5    <e199fvgn0cfuqcaa93l0hbk3k6o8gu2g7n@4ax.com> ...
6            Subject: Re: Is This A New Virus Attack?
7                                       X-Priority: 3
8                           X-MSMail-Priority: Normal
9   X-Newsreader: Microsoft Outlook Express 6.00.2...
10  X-MimeOLE: Produced By Microsoft MimeOLE V6.00...
11                                           Lines: 7
12  Message-ID: <3ef615b0$0$45177$65c69314@mercury...
13                 NNTP-Posting-Host: 213.208.117.241
14  X-Trace: 1056314800 mercury.nildram.net 45177 ...
15  Xref: intern1.nntp.aus1.giganews.com uk.politi...
16   uk.politics.misc:1162979 alt.politics.british...
17   soc.culture.british:800188 alt.journalism.new...
18                alt.politics.usa.republican:1690857
19     Jon° <jon_jon106@yahoo.co.uk> wrote in message
20                     news:3ef4b30b@212.67.96.135...
21         > You mean your kids are shagging already?
22                   *plonk* for another gutter-brain
23               From nobody Fri Jun 13 18:36:03 2014
24  Path: news5.aus1.giganews.com!firehose2!nntp4!...
25                X-Trace-PostClient-IP: 24.77.109.44
26             From: "wha' da way" <whadaway@shaw.ca>
27                                 alt.conspiracy.jfk
28  References: <9s2Ja.254938$ro6.6586887@news2.ca...
29       <aakbfv4rhji27jfocoqh3vdagb0e6hvvki@4ax.com>

In [77]:
df['references'].iloc[0]

'<9s2Ja.254938$ro6.6586887@news2.calgary.shaw.ca> <aakbfv4rhji27jfocoqh3vdagb0e6hvvki@4ax.com>'

In [78]:
df_messages_new

                       From nobody Fri Jun 13 18:36:02 2014
0         Path: news5.aus1.giganews.com!firehose2!nntp4!...
1         From: "Andrew Fenton" <andrew-fenton@spammers....
2                               alt.politics.usa.republican
3                      References: <3ef17faa@212.67.96.135>
4          <Cc1Ja.1314$SJ5.11403450@news-text.cableinet....
...                                                     ...
66838540                                                --
66838541                                    www.abelard.org
66838542                                                ---
66838543  This email is free from viruses and malware be...
66838544                               http://www.avast.com

[66838545 rows x 1 columns]

In [79]:
ref_id=df['references'].str.split()

In [80]:
print(df_messages_new.iloc[30])

From nobody Fri Jun 13 18:36:02 2014    Subject: Re: But is he good in bed?
Name: 30, dtype: object

In [81]:
ref_id[0]

['<9s2Ja.254938$ro6.6586887@news2.calgary.shaw.ca>',
 '<aakbfv4rhji27jfocoqh3vdagb0e6hvvki@4ax.com>']

In [82]:
df['subject'].iloc[0]

'Re: But is he good in bed?'

In [83]:
df['msg_id'].iloc[0]
df['msg_id'].iloc[0:50]

0      <RVnJa.288812$Vi5.7523594@news1.calgary.shaw.ca>
1       <3ef615b0$0$45177$65c69314@mercury.nildram.net>
2      <DHoJa.289156$Vi5.7536157@news1.calgary.shaw.ca>
3     <984a2ef1.0306221459.6bba9d5f@posting.google.com>
4      <f1fd22d4.0306221637.7001d05@posting.google.com>
5             <bd5lu2$pov5g$1@ID-186693.news.dfncis.de>
6                 <3EF66174.5010901@doodah.doobrie.net>
7          <sibdfv8aq45mj65vpfuftklba9637ec6jk@4ax.com>
8          <k4cdfvs0osg0adoonmrubom1o1cs9nvl5b@4ax.com>
9     <59b7797b.0306230037.440227e9@posting.google.com>
10    <f890d8e3.0306230101.6ae611c6@posting.google.com>
11    <f890d8e3.0306230107.54577a18@posting.google.com>
12                             <3ef6c324@212.67.96.135>
13                             <3ef6cfdb@212.67.96.135>
14                             <3ef6d2bf@212.67.96.135>
15                             <3ef6d33e@212.67.96.135>
16            <bd6kgl$puapd$1@ID-152947.news.dfncis.de>
17                             <3ef6d489@212.67.96.135>
18            <bd6lvm$pekcn$1@ID-186693.news.dfncis.de>
19                             <3ef6db4b@212.67.96.135>
20    <Z2VybWFueQ==.ab3d387318b5c04f168e92f4cb672235...
21                           <07bSdbCilv9+Ew9$@aol.com>
22                 <bd73dg$9ld$1@sparta.btinternet.com>
23                 <bd73k9$9v5$1@sparta.btinternet.com>
24    <Xns93A3A2B275C7Astevenbrownbtopenwor@130.133....
25     <3ef715ec$0$30819$afc38c87@news.optusnet.com.au>
26            <bd78ee$psnhm$1@ID-162217.news.dfncis.de>
27                             <3ef725a1@212.67.96.135>
28      <xjGJa.2149$ps6.294907@ursa-nb00s0.nbnet.nb.ca>
29                     <bd7e4o$iqr$1@news.chatlink.com>
30            <bd7g99$pdt13$1@ID-120108.news.dfncis.de>
31                 <bd7hd8$2p3$1@sparta.btinternet.com>
32     <3ef74927$0$31277$afc38c87@news.optusnet.com.au>
33                             <3ef75cdb@212.67.96.135>
34         <3ef78a3b$0$7741$fa0fcedb@lovejoy.zen.co.uk>
35    <EGKJa.1234$5q2.188353@newsfep1-win.server.ntl...
36      <5JKJa.2254$ps6.308186@ursa-nb00s0.nbnet.nb.ca>
37    <1a7b6469.0306231427.107de110@posting.google.com>
38         <3ef78a3d$0$7741$fa0fcedb@lovejoy.zen.co.uk>
39      <SiMJa.379$pc.369@news-binary.blueyonder.co.uk>
40           <nj3Ka.7717$eE.75352@nasal.pacific.net.au>
41           <pj3Ka.7718$eE.75359@nasal.pacific.net.au>
42              <Xns93A3B1317F29EWSAP1960@64.164.98.29>
43                   <bd867d$p7d$1@bunyip.cc.uq.edu.au>
44            <bd89rf$q5cj7$1@ID-139981.news.dfncis.de>
45      <VFOJa.540$g_1.2933@news-server.bigpond.net.au>
46                                 <3ef7c8db@shknews01>
47                   <BB1D2770.1FAB%core@mtolympus.com>
48                   <BB1D2977.1FD6%core@mtolympus.com>
49         <movffvs9jv2d3rvilcr0nca9tedljuesk6@4ax.com>
Name: msg_id, dtype: object

In [84]:
df_messages_new.iloc[0:70]

                 From nobody Fri Jun 13 18:36:02 2014
0   Path: news5.aus1.giganews.com!firehose2!nntp4!...
1   From: "Andrew Fenton" <andrew-fenton@spammers....
2                         alt.politics.usa.republican
3                References: <3ef17faa@212.67.96.135>
4    <Cc1Ja.1314$SJ5.11403450@news-text.cableinet....
..                                                ...
65  > past should be allowed to continue defies bo...
66  > can never achieve the consoling sanctity and...
67  > with their Human Companion. Some indeed are ...
68  > disheartening spectacle. I urge everyone int...
69  > fairness issues to bring this matter up at t...

[70 rows x 1 columns]

In [85]:
df_messages_new[140:160]

                  From nobody Fri Jun 13 18:36:02 2014
140                                                 JH
141               From nobody Fri Jun 13 18:36:03 2014
142              From: "Jon°" <jon_jon106@yahoo.co.uk>
143                Subject: Don't Bash  Your Bishops.
144                                          Lines: 40
145                                      X-Priority: 3
146                          X-MSMail-Priority: Normal
147  X-Newsreader: Microsoft Outlook Express 6.00.2...
148  X-MimeOLE: Produced By Microsoft MimeOLE V6.00...
149                   NNTP-Posting-Host: 213.78.107.54
150               Message-ID: <3ef6c324@212.67.96.135>
151  Path: news5.aus1.giganews.com!firehose2!nntp4!...
152  Xref: intern1.nntp.aus1.giganews.com uk.politi...
153   uk.politics.misc:1163370 alt.politics.british...
154   soc.culture.british:800362 alt.journalism.new...
155   alt.politics.usa.republican:1691212 soc.cultu...
156  Languages and "alternative sex" at Hertford Co...
157         therefore be described as a "loose canon".
158  He returned to Oxford in 1980 to read for a do...
159  and was also instructed in  "Studies Of Male S...

In [86]:
df_messages_new["msg_parts"]=df_messages_new['From nobody Fri Jun 13 18:36:02 2014']
df_messages_new.drop(columns=['From nobody Fri Jun 13 18:36:02 2014'],inplace=True)

In [87]:
import re 
match="From:"

for i,j in enumerate(df_messages_new["msg_parts"].iloc[:250]):
    found=re.match(match,j)
    if found:
        print(i,j)

1 From: "Andrew Fenton" <andrew-fenton@spammers.lineone.canpissoff.net>
26 From: "wha' da way" <whadaway@shaw.ca>
80 From: ianbailey@orange.net (Ian Bailey)
114 From: John Hill <johnthewealthbuilder@opera.com>
142 From: "Jon°" <jon_jon106@yahoo.co.uk>
179 From: "Nicolas Benicoeur" <dontspambenicoeur@hotmail.com>
229 From: Oobie Doobie <oobied00bie@doodah.doobrie.net>

In [88]:
df_messages_new.iloc[235]

msg_parts    Reply-To: oobied00bie@doodah.doobrie.net
Name: 235, dtype: object

In [89]:

df_messages_new.iloc[26:34]

                                            msg_parts
26             From: "wha' da way" <whadaway@shaw.ca>
27                                 alt.conspiracy.jfk
28  References: <9s2Ja.254938$ro6.6586887@news2.ca...
29       <aakbfv4rhji27jfocoqh3vdagb0e6hvvki@4ax.com>
30                Subject: Re: But is he good in bed?
31                                          Lines: 57
32                                      X-Priority: 3
33                          X-MSMail-Priority: Normal

In [90]:
import re 
match="Subject:"

for i,j in enumerate(df_messages_new["msg_parts"].iloc[:250]):
    found=re.match(match,j)
    if found:
        print(i,j)

6 Subject: Re: Is This A New Virus Attack?
30 Subject: Re: But is he good in bed?
82 Subject: Re: CASTRATED CONSERVATIVES FUCK UP (AGAIN) on  "EU CONSTITUTION"
116 Subject: Re: Why Do Nu labour Hate Men So Much?
143 Subject: Don't Bash  Your Bishops.
181 Subject: Jewish MP compares Gaza to the Warsaw Ghetto

In [91]:
df_messages_new["msg_parts"].iloc[6:30]

6              Subject: Re: Is This A New Virus Attack?
7                                         X-Priority: 3
8                             X-MSMail-Priority: Normal
9     X-Newsreader: Microsoft Outlook Express 6.00.2...
10    X-MimeOLE: Produced By Microsoft MimeOLE V6.00...
11                                             Lines: 7
12    Message-ID: <3ef615b0$0$45177$65c69314@mercury...
13                   NNTP-Posting-Host: 213.208.117.241
14    X-Trace: 1056314800 mercury.nildram.net 45177 ...
15    Xref: intern1.nntp.aus1.giganews.com uk.politi...
16     uk.politics.misc:1162979 alt.politics.british...
17     soc.culture.british:800188 alt.journalism.new...
18                  alt.politics.usa.republican:1690857
19       Jon° <jon_jon106@yahoo.co.uk> wrote in message
20                       news:3ef4b30b@212.67.96.135...
21           > You mean your kids are shagging already?
22                     *plonk* for another gutter-brain
23                 From nobody Fri Jun 13 18:36:03 2014
24    Path: news5.aus1.giganews.com!firehose2!nntp4!...
25                  X-Trace-PostClient-IP: 24.77.109.44
26               From: "wha' da way" <whadaway@shaw.ca>
27                                   alt.conspiracy.jfk
28    References: <9s2Ja.254938$ro6.6586887@news2.ca...
29         <aakbfv4rhji27jfocoqh3vdagb0e6hvvki@4ax.com>
Name: msg_parts, dtype: object

In [92]:
df_messages_new["msg_parts"].iloc[:6]

0    Path: news5.aus1.giganews.com!firehose2!nntp4!...
1    From: "Andrew Fenton" <andrew-fenton@spammers....
2                          alt.politics.usa.republican
3                 References: <3ef17faa@212.67.96.135>
4     <Cc1Ja.1314$SJ5.11403450@news-text.cableinet....
5     <e199fvgn0cfuqcaa93l0hbk3k6o8gu2g7n@4ax.com> ...
Name: msg_parts, dtype: object

In [93]:
match="References:"

for i,j in enumerate(df_messages_new["msg_parts"].astype(str).iloc[:280]):
    found=re.match(match,j)
    if found:
        print(i,j)

3 References: <3ef17faa@212.67.96.135>
28 References: <9s2Ja.254938$ro6.6586887@news2.calgary.shaw.ca>
87 References: <3ef39beb$0$7733$fa0fcedb@lovejoy.zen.co.uk>
120 References: <3ef19204@212.67.96.135>
233 References: <bd326d$oqai3$1@ID-186693.news.dfncis.de>
279 References: <bd326d$oqai3$1@ID-186693.news.dfncis.de>

In [94]:
senders=[]
cols=["index","sender"]


match="From:"

for i,j in enumerate(df_messages_new["msg_parts"].astype(str)):
    found=re.match(match,j)
    if found:
        senders.append({"index":i,"sender":j})


senders=pd.DataFrame(senders,columns=cols)

In [95]:
match="Xref:"

for i,j in enumerate(df_messages_new["msg_parts"].astype(str).iloc[:10]):
    found=re.match(match,j)
    if found:
        print(i,j.split())


print(df_messages_new['msg_parts'].iloc[49])

> >I note with some consternation an Associated Press article in yesterday's

In [ ]:
group_pattern = re.compile(r"^(alt|comp|soc|rec|talk|news|sci|misc|humanities|uk|aus|de|fr|can|nl)\.[\w\.\-]+")
match_sender = re.compile(r"^From:")
match_subject = re.compile(r"^Subject:")
match_ref = re.compile(r"^References:")
match_msgid = re.compile(r"^Message-ID:")
match_xref = re.compile(r"^Xref:")

cleaned_df = []
columns = ['index', 'sender', 'subject', 'references', 'groups', 'body', 'msg_id']
msg_parts = df_messages_new["msg_parts"].astype(str)
i = 0

while i < len(msg_parts):
    row = {'index': i, 'sender': None, 'subject': None, 'references': None, 'groups': None, 'body': "", 'msg_id': None}
    while i < len(msg_parts):
        line = msg_parts.iloc[i]

        if match_sender.match(line):
            row['sender'] = line.replace("From:", "").strip()

        elif match_subject.match(line):
            row['subject'] = line.replace("Subject:", "").strip()

        elif match_ref.match(line):
            row['references'] = line.replace("References:", "").strip()

        elif match_msgid.match(line):
            row['msg_id'] = line.replace("Message-ID:", "").strip()

        elif match_xref.match(line):
            groups = group_pattern.findall(line)
            row['groups'] = ",".join(groups) if groups else None

        elif i+1 < len(msg_parts) and match_sender.match(msg_parts.iloc[i+1]):
            break

        else:
            row['body'] += line + "\n"

        i += 1

    cleaned_df.append(row)
    i += 1  


df_cleaned = pd.DataFrame(cleaned_df, columns=columns)

In [ ]:
print(df_messages_new['msg_parts'].iloc[26:80])

In [ ]:
#match="Message-ID:"

#for i,j in enumerate(df_messages_new["msg_parts"].astype(str).iloc[:180]):
#    found=re.match(match,j)
#    if found:
#        print(i,j)

In [ ]:
df_cleaned['references'].value_counts()

In [ ]:
msg_id=df_cleaned[df_cleaned['references']=='<i374b.131$QD3.4402@eagle.america.net>']['msg_id']

In [ ]:
df_cleaned[df_cleaned['references']=='<i374b.131$QD3.4402@eagle.america.net>']

In [ ]:
df_cleaned[df_cleaned['references']=='<bleto9$aig$5@news8.svr.pol.co.uk>']

In [ ]:
# Step 1: Build a lookup dictionary for msg_id → row index
msgid_to_index = df_cleaned.groupby('msg_id')['index'].apply(list).to_dict()

# Step 2: Build a reference mapping tree (msg_id → list of replies)
from collections import defaultdict

thread_tree = defaultdict(list)

for idx, row in df_cleaned.iterrows():
    ref = row['references']
    if ref and ref in msgid_to_index:
        thread_tree[ref].append(row['msg_id'])  # this message is a reply to `ref`

In [ ]:
# 1. Build child-to-parent map
msg_to_parent = {}

for parent, replies in thread_tree.items():
    for child in replies:
        msg_to_parent[child] = parent

# 2. Calculate depth recursively
depths = {}

def get_depth(msg_id, visited=None):
    if visited is None:
        visited = set()
    if msg_id in visited:
        return 0  # break circular loop

    visited.add(msg_id)

    if msg_id not in msg_to_parent:
        return 0  # root node

    parent = msg_to_parent[msg_id]

    if parent not in depths:
        depths[parent] = get_depth(parent, visited)

    return depths[parent] + 1

# 3. Apply depth calculation to all msg_ids
for msg_id in df_cleaned['msg_id']:
    depths[msg_id] = get_depth(msg_id)

# 4. Add depth info to DataFrame
df_cleaned['depth'] = df_cleaned['msg_id'].map(depths)

In [ ]:
df_cleaned['depth'].value_counts()

In [ ]:
# Just create a parent-child DataFrame
thread_links = df_cleaned[['msg_id', 'references']].dropna()
thread_links = thread_links[thread_links['references'] != '']

In [ ]:
thread_links

In [ ]:
df_cleaned[df_cleaned['references']=='<i374b.131$QD3.4402@eagle.america.net>']['body'].iloc[0]

In [ ]:
df_cleaned["body"].iloc[2]